spring:
  application:
    name: petspring
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/abrigo?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
